version: '3'
services:
  kc_db:
    image: postgres:15.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: keycloak_db
    ports:
      - "5433:5433"
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.1
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: kc_db
      DB_DATABASE: keycloak_db
      DB_USER: my_admin
      DB_SCHEMA: public
      DB_PASSWORD: my_password
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: kc_password
    depends_on:
     - kc_db
#  neo4j:
#    image: neo4j:5.15.0
#    ports:
#      - "7474:7474"
#      - "7687:7687"
#    environment:
#      NEO4J_AUTH: neo4j/strong_password
#  postgres:
#    container_name: news
#    image: postgres
#    environment:
#      POSTGRES_DB: news
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      PGDATA: /data/postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - news:/data/postgres
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
#    container_name: elasticsearch_container
#    ports:
#      - "9200:9200"
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#  mongo:
#    container_name: mongo-db
#    image: mongo
#    restart: always
#    ports:
#      - "27018:27017"
#    volumes:
#      - mongo:/data/mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongouser
#      MONGO_INITDB_ROOT_PASSWORD: mongopassword
#  minio:
#    container_name: minio-storage
#    image: minio/minio:latest
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#      MINIO_ACCESS_KEY_FILE: access_key
#      MINIO_SECRET_KEY_FILE: secret_key
#    volumes:
#      - minio_storage:/data
#    command: server --console-address ":9001" /data
#  rabbitmq:
#    image: rabbitmq:3.10.7-management
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
#    ports:
#      - "15672:15672"
#      - "5672:5672"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  news:
  mongo:
  minio_storage:
#  redis:

