version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_container
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#  mongo:
#    container_name: mongo-db
#    image: mongo
#    restart: always
#    ports:
#      - "27018:27017"
#    volumes:
#      - mongo:/data/mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongouser
#      MONGO_INITDB_ROOT_PASSWORD: mongopassword
#  minio:
#    container_name: minio-storage
#    image: minio/minio:latest
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#      MINIO_ACCESS_KEY_FILE: access_key
#      MINIO_SECRET_KEY_FILE: secret_key
#    volumes:
#      - minio_storage:/data
#    command: server --console-address ":9001" /data
#  rabbitmq:
#    image: rabbitmq:3.10.7-management
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#  redis:
#    image: "redis/redis-stack:latest"
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis:/redis/redis-data:/data
#      - redis:/redis/redis-conf:/usr/local/etc/redis/redis.conf
#volumes:
#  mongo:
#  minio_storage:
#  redis: