spring:
  cloud:
    openfeign:
      client:
        config:
          storage-service-client:
            url: http://localhost:7070/api/v1/file
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
server:
  port: 8888
  servlet:
    context-path: /api/v1
logging:
  level:
    org.springframework:
      web: debug
      cloud:
        openfeign: debug