server:
  port: 8082
spring:
  main:
    web-application-type: reactive
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: qr-service
          uri: http://localhost:7070
          predicates:
            - Path=/api/v1/qr/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8080
        registration:
          reg-client:
            provider: spring
            client-id: demo
            client-secret: "secret"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user.read,user.write,openid
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

logging:
  level:
    org.springframework:
      web: debug
      security: debug

