FROM eclipse-temurin:17.0.4.1_1-jre

COPY target/url-shortener-service-0.0.1-SNAPSHOT.jar url-shortener-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java" , "-jar" , "/url-shortener-service-0.0.1-SNAPSHOT.jar"]