name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths:
      - 'api-gateway/**'
      - 'auth-service/**'
      - 'mail-service/**'
      - 'qr-service/**'
      - 'storage-service/**'
      - 'url-shortener-service.yml/**'
      - 'post-service/**'
      - 'user-service/**'
      - 'logging-spring-boot-starter/**'

jobs:
  changes:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api-gateway:
              - 'api-gateway/**'
            auth-service:
              - 'auth-service/**'
            mail-service:
              - 'mail-service/**'
            qr-service:
              - 'qr-service/**'
            storage-service:
              - 'storage-service/**'
            url-shortener-service:
              - 'url-shortener-service/**'
            user-service:
              - 'user-service/**'
            post-service:
              - 'post-service/**'            

      - name: Check changes for each service
        run: |
          echo "Changed files: ${{ github.event_name }} ${{ github.event.before }}...${{ github.sha }}"
          echo "Changed services: ${{ steps.changes.outputs.services }}"
        env:
          SERVICES: ${{ steps.changes.outputs.services }}
    outputs:
      api-gateway: ${{ steps.changes.outputs.api-gateway }}
      auth-service: ${{ steps.changes.outputs.auth-service }}
      mail-service: ${{ steps.changes.outputs.mail-service }}
      qr-service: ${{ steps.changes.outputs.qr-service }}
      storage-service: ${{ steps.changes.outputs.storage-service }}
      url-shortener-service: ${{ steps.changes.outputs.url-shortener-service.yml }}

  qr-service:
    needs: changes
    if: ${{ needs.changes.outputs.qr-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Qr service
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f qr-service/pom.xml -DskipTests

      - name: Build Docker Image Qr service
        run: docker build -t daneker/qr-service -f qr-service/Dockerfile qr-service/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image Qr service
        run: docker push daneker/qr-service

  mail-service:
    needs: changes
    if: ${{ needs.changes.outputs.mail-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Mail service
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f mail-service/pom.xml -DskipTests

      - name: Build Docker Image Mail service
        run: docker build -t daneker/mail-service -f mail-service/Dockerfile mail-service/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image Mail service
        run: docker push daneker/mail-service

  auth-service:
    needs: changes
    if: ${{ needs.changes.outputs.auth-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Auth service
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f auth-service/pom.xml -DskipTests

      - name: Build Docker Image Auth service
        run: docker build -t daneker/auth-service -f auth-service/Dockerfile auth-service/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image Auth service service
        run: docker push daneker/auth-service
  api-gateway:
    needs: changes
    if: ${{ needs.changes.outputs.api-gateway == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Api gateway
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f api-gateway/pom.xml -DskipTests

      - name: Build Docker Image Api Gateway
        run: docker build -t daneker/api-gateway -f api-gateway/Dockerfile api-gateway/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image Api gateway service
        run: docker push daneker/api-gateway
  url-shortener-service:
    needs: changes
    if: ${{ needs.changes.outputs.url-shortener-service.yml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Url shortener
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f url-shortener-service.yml/pom.xml -DskipTests

      - name: Build Docker Image Url Shortener
        run: docker build -t daneker/url-shortener-service.yml -f url-shortener-service.yml/Dockerfile url-shortener-service.yml/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image Url shortener service
        run: docker push daneker/url-shortener-service.yml
  user-service:
    needs: changes
    if: ${{ needs.changes.outputs.user-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository User servuce
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f user-service/pom.xml -DskipTests

      - name: Build Docker User service Shortener
        run: docker build -t daneker/user-service -f user-service/Dockerfile user-service/

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Push Docker Image user service
        run: docker push daneker/user-service
  post-service:
    needs: changes
    if: ${{ needs.changes.outputs.post-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: To be implemented
        run: echo "To be implemented"
  storage-service:
    needs: changes
    if: ${{ needs.changes.outputs.storage-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: To be implemented
        run: echo "To be implemented"



