spring:
  application:
    name: mail-service
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@social-network.com
    port: 587
  rabbitmq:
    queues:
      news-letter:
        routing-key: news-letter.routing-key
        name: news-letter.queue
        exchange: news-letter.exchange
    username: user
    password: password
    host: localhost
  freemarker:
    template-loader-path: "classpath:/templates"