spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@localhost:27018/channel.Channel?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_SERVER:http://localhost:8080}/auth/realms/socialapp
          jwk-set-uri: ${OAUTH2_SERVER:http://localhost:8080}/auth/realms/socialapp/protocol/openid-connect/certs
  cloud:
    openfeign:
      client:
        config:
          storage-service-client:
            url: http://localhost:7070/api/v1/file