spring:
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:7070/api/v1/storage/
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  data:
    elasticsearch:
      should-create-index:
        socialapp.userservice.model.entity.User
      url: localhost:9200
      connection-timeout: 1000 # 1 second
#      username: username
#      password: password
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  application:
    name: user-service
  neo4j:
    authentication:
      password: strong_password
      username: neo4j

resilience4j:
  retry:
    metrics:
      enabled: true
    instances:
      storage-service:
        max-attempts: 2
        fail-after-max-attempts: false
  circuitbreaker:
    metrics:
      enabled: true
    instances:
      storage-service:
        register-health-indicator: true
        sliding-window-size: 50
        sliding-window-type: TIME_BASED
        slow-call-rate-threshold: 2f
        minimumNumberOfCalls: 5
        writable-stack-trace-enabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        enable-exponential-backoff: true
        slow-call-duration-threshold: 2s

