spring:
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            follow-redirects: true
            url: http://localhost:8080
            connectTimeout: 5000
            readTimeout: 5000
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/socialapp
          jwk-set-uri: http://localhost:8080/auth/realms/socialapp/protocol/openid-connect/certs
  application:
    name: chat-service
  data:
    redis:
      master:
        host: localhost
        port: 6379
      slaves:
        - host: localhost
          port: 6379
server:
  port: 9393
logging:
  level:
    org.springframework:
      web: debug
      security: debug
cors:
  allowCredentials: false
  allowedOrigins: http://localhost:4200,http://127.0.0.1:5500
  allowedMethods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowedHeaders: origin,content-type,accept,authorization,cookie