name: CI CD Api gateway

on:
  push:
    branches: [ master ]
    paths:
      - 'api-gateway/**'

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository api gateway
        uses: actions/checkout@v2

      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean install --file api-gateway/pom.xml

      - name: Build and Push Docker Image
        run: |
          docker build -t daneker/api-gateway:latest api-gateway
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker push
        run: docker push daneker/api-gateway:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}