name: CI CD Api gateway

on:
  push:
    branches: [ master ]
    paths:
      - 'api-gateway/**'

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository api gateway
        uses: actions/checkout@v2

      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean install --file api-gateway/pom.xml

      - name: Build and Push Docker Image
        run: |
            docker build -t api-gateway api-gateway
            docker tag api-gateway $DOCKER_USERNAME/api-gateway
            docker push $DOCKER_USERNAME/api-gateway
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}