name: CI CD Api gateway

on:
  push:
    branches: [ master ]
    paths:
      - 'api-gateway/**'

jobs:
  api-gateway:
    uses: youngAndMad/deploy/.github/workflows/ci-cd.yml@master
    with:
      maven-command: 'mvn -B clean install --file api-gateway/pom.xml'
      docker-image-name: 'daneker/api-gateway:latest'
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}