name: CI CD Logging starter

on:
  push:
    branches: [ master ]
    paths:
      - 'logging-spring-boot-starter/**'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'false'


jobs:
  changes:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            logging-starter:
              - 'logging-spring-boot-starter/**'
      - name: Check changes for each service
        run: |
          echo "Changed files: ${{ github.event_name }} ${{ github.event.before }}...${{ github.sha }}"
          echo "Changed services: ${{ steps.changes.outputs.services }}"
        env:
          SERVICES: ${{ steps.changes.outputs.services }}
    outputs:
      logging-starter: ${{ steps.changes.outputs.logging-starter }}


  logging-starter:
    name: Push to nexus
    runs-on:  ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.logging-starter == 'true' }}
    steps:
      - name: Checkout Repository Logging starter
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          server-id: mine-nexus-releases
      - name: Push to nexus with maven
        run: |
          mvn clean --batch-mode deploy 
          -f logging-spring-boot-starter/pom.xml -DskipTests -Dmaven.install.skip=true  
          -Dnexus.host=${{ secrets.NEXUS_URL }} -Dnexus.username=${{ secrets.NEXUS_USERNAME }}
          -Dnexus.password=${{ secrets.NEXUS_PASSWORD }}
