name: CI CD Storage service

on:
  push:
    branches: [ master ]
    paths:
      - 'storage-service/**'

jobs:
  storage-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Docker build
        run: |
          cd storage-service
          docker build -t daneker/storage-service .
          docker tag daneker/storage-service daneker/storage-service:latest
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: docker push daneker/storage-service:latest
