name: CI CD User service

on:
  push:
    branches: [ avoid_ci_cd ]
    paths:
      - 'user-service/**'

jobs:
  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository api gateway
        uses: actions/checkout@v2

      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean install --file user-service/pom.xml

      - name: Build and Push Docker Image
        run: |
          docker build -t daneker/user-service:latest user-service
      - name: Docker login
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: docker push daneker/user-service:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}